--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/hachkingtohach1/CustomCraftDraz
build-by-default: true
branches:
- master
projects:
  CustomCraftDraz:
    path: "CustomCraft.png"
...
