---
# Item_1 is default name
# You can change name
# Example: nam, dragovn, etc
Item_1:
  shape:
    - [[0], ["260:0"], [0]]
    - [["260:0"], ["260:0"], ["260:0"]]
    - [[0], ["260:0"], [0]]
  result:  ["278:0", 1]
  # enable_enchant: false => not working
  enable_enchant: true
  # enable_cenchant: false => not working
  enable_cenchant: true
  enchantment:
    9: 1
  cenchantment:
    haste: 1
...

